# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  
#  adding  Node Exporter  to get  Hardware and Os level metrics from any source having linux or mac os 
  - job_name: 'node-exporter1'
    static_configs:
    - targets: ['192.168.12.241:9100']    
#  adding  application server to get http related metrics using python http server 

  - job_name: 'http-app-server-1'
    static_configs:
    - targets: ['192.168.4.63:8000']    

#  adding  docker engine metric to prometheus
  - job_name: 'node-docker-engine'
    static_configs:
    - targets: ['192.168.12.241:9323']    

